### ISSUE TITLE
Regression from 4.0: You can no longer send a streamed response

### ISSUE THREAD

**Issue by BenWoodford** [scottoffen/grapevine#102]
In 4.0 I could write to the output stream in chunks, and then close the stream and the response. But I guess now, Grapevine checks and tries to close the response without checking if it's already closed resulting in an exception at the end of the response (after all the data has already been sent)

In theory just checking if the response has closed first would be sufficient, but a more sensible system would be to have a "MarkComplete"-like method so we can manually handle the outputstream and then let Grapevine know that the response is finished.

**Comment by scottoffen** [comment]
Can you provide a code sample of what you are referring to? Both from 4.0 and what you are seeing in 5.0 would be helpful.

**Comment by BenWoodford** [comment]
Essentially if I wrote to the Output stream directly I could then do this in 4.0:

```
            context.Response.Advanced.OutputStream.Close();
            context.Response.Advanced.Close();
```

And all would be well.

But now it seems that an attempt is made (and exception thrown) to close it as though I haven't sent any data as `ResponseSent` is not set to true. I've sorted it on my end by adding this to `HttpResponse.cs` and calling it after closing the output stream:

```
        public void MarkSent() {
            ResponseSent = true;
            Advanced.Close();
        }
```

**Comment by scottoffen** [comment]
I see. So you are using the `HttpResponse.Advanced` field to write directly to the output stream, and then closing the output stream and the `HttpListenerResponse` yourself, but you aren't setting the `ResponseSent` property of the `HttpResponse` at the same time, which is what would happen if you called `SendResponseAsync`.

If you are going to circumvent the `SendResponseAsync` method, then you will need to set the `ResponseSend` property yourself, too. But you can't set that field directly because of it's accessors.

So, you need a way to mark it as sent when you bypass the `SendResponseAsync` method, right?

**Comment by BenWoodford** [comment]
Correct. Which I've done with a `MarkComplete` method in my fork which closes the stream and marks it as sent for now
