### ISSUE TITLE
How to set the character set value of the Content-Type response header

### ISSUE THREAD

**Issue by Hyrius** [scottoffen/grapevine#113]
Hi! I started playing with **Grapevine** recently, but still couldn't figure out how to properly respond with **UTF-8 characters**. 
For example, "Injeção" becomes "InjeÃ§Ã£o". 
Among other things, I tried setting **Response.ContentEncoding** to **Text.Encoding.UTF8**, but nothing seemed to work. 
What am I doing wrong?

**Comment by scottoffen** [comment]
The `HttpResponse.ContentEncoding` property is used in conjunction with the request output stream, and maps directly to the [HttpListenerResponse.ContentEncoding property](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistenerresponse.contentencoding?view=net-6.0). The property is set to `Encoding.UTF8` by Grapevine by default.

This property is not related to the [`Content-Encoding` http response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding), which is used to communicate content encoding to the client, and is most commonly used to indicated that the response body has been compressed.

Neither of these are related to the [character set](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) being used in the response body.

The changing of the text (which is only an issue in browsers, try with Postman and it doesn't happen) is because there is not currently a default value for the character set used in the response body. In future versions of Grapevine, a default will be provided to avoid this issue going forward.

Meanwhile, you can provide a value per response:
```csharp
context.Response.ContentType = "text/plain; charset=UTF-8";
```

**Comment by scottoffen** [comment]
This updated will be in the next release.
