### ISSUE TITLE
How to disable the logger?

### ISSUE THREAD

**Issue by diabolical17** [scottoffen/grapevine#21]
Self explanatory.

**Comment by scottoffen** [comment]
If you are not using the `RestServerBuilder` class, it's easy to disable to logger. Just don't configure one and one will not be added.

If  you are using the `RestBuilderServer` class, a console logger is injected by default. You can remove/change that when configuring services.

```csharp
public void ConfigureServices(IServiceCollection services)
{
    // Change the logging level if it's too much
    services.Configure<LoggerFilterOptions>(options => options.MinLevel = LogLevel.Critical);

    // Remove logging altogether
    services.AddLogging(logging => logging.ClearProviders());
}
```

You should always clear providers before adding your preferred provider (e.g. NLog, Serilog, etc.)

A reminder that, at the time of this writing, Grapevine 5 is still in pre-release, and changes are being made as the documentation is being written. In the future, please post "how to" questions to the [community discussion boards](https://github.com/scottoffen/grapevine/discussions) rather than as an issue.

And thanks for using Grapevine!
