### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by ghostravenstorm** [scottoffen/grapevine#56]
Trying to setup something simple for external logging purposes using rest endpoints on a server built in .NET.
Are there any examples of a more complete setup using Grapevine? Something that goes beyound localhost testing?
Like being able to set the host IP and port? I'm not sure where this is done.

**Comment by scottoffen** [comment]
You will need [configure a namespace reservation](https://scottoffen.github.io/grapevine/docs/tutorials/configure-namespace-reservation) and possibly [open the windows firewall](https://scottoffen.github.io/grapevine/docs/tutorials/windows-firewall), depending on exactly what you want to accomplish.

In the future, please consider asking usage questions in the [discussions](https://github.com/scottoffen/grapevine/discussions) section, rather than opening an issue, per the contributing guidelines.
