### ISSUE TITLE
Stack overflow crash when unknown route received

### ISSUE THREAD

**Issue by Soren025** [scottoffen/grapevine#57]
![Stack Trace](https://puu.sh/HD7bS/34927e45f1.png)

This happens with the sample project if you provide a route not defined. `http://localhost:1234/asdfg` for example.

This will also happen with the sample code shown in the project readme if the request is made in the browser. This is because the browser requests for the `favicon.ico` to which there is no route for that defined.

**Comment by danieletoffetti** [comment]
The problem is in RouterBaseExtensions.HandleHttpListenerExceptions, RouterBase.DefaultErrorHandler is not preserved, so the handler keeps calling itself. Easiest fix is to comment out rows 101-102 in RestServer.cs:
    //if (Router is RouterBase)
             //   (Router as RouterBase).HandleHttpListenerExceptions();
 
 Fix is only temporarily of course while the author (who did a great job by the way, I like Grapevine very much) posts a better one.

**Comment by scottoffen** [comment]
Great catch! I'll check in a fix, but it might be a few days before I can get this into a nuget package.

**Comment by scottoffen** [comment]
@Soren025 or @danieletoffetti would one of you mind verifying that this branch resolves your issue before I merge it in?
https://github.com/scottoffen/grapevine/tree/stack-overflow-crash

**Comment by danieletoffetti** [comment]
yes, issue is resolved with this fix. Nice, thanks!
